# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc54ab4efdda4bad2eed3b6fb6ebd9da0d8377e49946e5dd53cff32e7637d49bbbc4863bbf59c189558bec089261a484f93fb6e4642ca3e669d3296e17c461b6

test:
  secret_key_base: 26f6c88df0c5a7b055ae8e04780c771ce88a5e0a9ccbb838d02fd8695f4b83e695add59be4fa5ea70651084adbdafbf42265984d6a16e9557896f21ff27154dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
